<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VTPLDSK084" name="Test" tests="6" failures="1" timestamp="20 May 2021 05:28:21 GMT" time="0.061" errors="0">
  <testcase name="failtest" time="0.02" classname="pack1.dataprovider">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at pack1.dataprovider.failtest(dataprovider.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- failtest -->
  <testcase name="webLoginCarLoan" time="0.02" classname="pack1.day5"/>
  <testcase name="apiLoginCarLoan" time="0.004" classname="pack1.day5"/>
  <testcase name="webLoginCarLoan" time="0.002" classname="pack1.dataprovider"/>
  <testcase name="webLoginCarLoan" time="0.001" classname="pack1.dataprovider"/>
  <testcase name="webLoginCarLoan" time="0.0" classname="pack1.dataprovider"/>
</testsuite> <!-- Test -->
